db_clients:
  indexinfo_dataset:
    db_type: sqlite               
    db_path: query_dataset/indexinfo_query.db  

  indextrade_dataset:
    db_type: duckdb               # Database type: DuckDB
    db_path: query_dataset/indextrade_query.db       # Path to the DuckDB file
