db_clients:
  stockinfo_dataset:
    db_type: sqlite               
    db_path: query_dataset/stockinfo_query.db  

  stocktrade_dataset:
    db_type: duckdb               # Database type: DuckDB
    db_path: query_dataset/stocktrade_query.db       # Path to the DuckDB file
